version: '3'
services:
  base:
    image: liuliujeng/pyspark-notebook:2.4.4-jdk8
    build:
      context: ./docker-stacks/pyspark-notebook
      args:
        spark_version: 2.4.4
        hadoop_version: 2.7
        spark_checksum: 2E3A5C853B9F28C7D4525C0ADCB0D971B73AD47D5CCE138C85335B9F53A6519540D3923CB0B5CEE41E386E49AE8A409A51AB7194BA11A254E037A848D0C4A9E5
        openjdk_version: 8
    ports:
      - 8888:8888
      - 4040:4040
  app:
    image: liuliujeng/spark:py3.6.5
    volumes:
      - work:/home/jovyan
    build:
      context: .
      dockerfile: Dockerfile
      args:
        conda_env: python36
        py_ver: 3.6.5
    ports:
      - 8888:8888
      - 4040:4040
